openapi: 3.0.0
info:
  title: Advanced Waste Management In Retail
  version: 1.0.0
  description: >
    API to manage and optimize waste management processes in retail environments,
    ensuring efficient waste handling, recycling, and resource utilization.

paths:
  '/waste/management':
    get:
      summary: Analyze waste management efficiency
      description: Retrieve analysis and recommendations for improving waste management processes in retail.
      responses:
        '200':
          description: Successful retrieval of waste management data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalWasteGenerated:
                    type: number
                    description: Total waste generated in kilograms.
                  recycledWaste:
                    type: number
                    description: Amount of waste recycled in kilograms.
                  optimizationSuggestions:
                    type: array
                    items:
                      type: object
                      properties:
                        wasteType:
                          type: string
                          description: Type of waste (e.g., plastic, paper, organic).
                        suggestion:
                          type: string
                          description: Optimization recommendation for the waste type.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/waste/disposal':
    post:
      summary: Simulate waste disposal scenarios
      description: Create and simulate waste disposal scenarios for enhanced waste management planning.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                storeId:
                  type: string
                  description: Unique identifier of the retail store.
                wasteCategories:
                  type: array
                  items:
                    type: string
                  description: Categories of waste generated (e.g., plastic, paper, organic).
                disposalMethods:
                  type: array
                  items:
                    type: string
                  description: Methods of waste disposal (e.g., recycling, landfill, incineration).
              required:
                - storeId
                - wasteCategories
                - disposalMethods
      responses:
        '201':
          description: Waste disposal simulation successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulationId:
                    type: string
                    description: Unique identifier of the waste disposal simulation.
                  status:
                    type: string
                    description: Current status of the simulation (e.g., in-progress, completed).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/optimization/waste':
    get:
      summary: Retrieve waste optimization suggestions
      description: Get waste optimization recommendations based on waste generation and disposal analysis.
      parameters:
        - name: storeId
          in: query
          required: true
          schema:
            type: string
          description: Unique identifier of the retail store.
      responses:
        '200':
          description: Successful retrieval of waste optimization suggestions.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    wasteType:
                      type: string
                      description: Type of waste (e.g., plastic, paper, organic).
                    recommendation:
                      type: string
                      description: Suggested improvement for waste handling.
                    expectedImpact:
                      type: string
                      description: Anticipated outcome of the recommendation (e.g., reduced landfill use, increased recycling).
        '400':
          description: Missing or invalid storeId parameter.
        '500':
          description: Internal server error.