openapi: 3.0.0
info:
  title: Analytics For Actionable Retail Insights
  version: 1.0.0
  description: >
    API to manage analytics for actionable retail insights, enabling businesses to
    transform data into meaningful insights for strategic decision-making and
    operational improvements.

paths:
  '/analytics/actionable-insights':
    get:
      summary: Retrieve actionable retail insights
      description: Fetch analytics data and actionable insights for retail operations.
      responses:
        '200':
          description: Successful retrieval of actionable retail insights.
          content:
            application/json:
              schema:
                type: object
                properties:
                  insightId:
                    type: string
                    description: Unique identifier of the insight.
                  insightCategory:
                    type: string
                    description: Category of the insight (e.g., sales, inventory, customer behavior).
                  insightDescription:
                    type: string
                    description: Description of the actionable insight.
                  impactLevel:
                    type: string
                    description: Impact level of the insight (e.g., low, medium, high).
                  recommendedActions:
                    type: array
                    items:
                      type: string
                    description: Recommended actions based on the insight.
                  lastUpdated:
                    type: string
                    format: date-time
                    description: Timestamp of the last update to the insight.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/analytics/actionable-insights/submit':
    post:
      summary: Submit data for actionable retail insights
      description: Submit data for generating actionable insights in retail.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                insightCategory:
                  type: string
                  description: Category of the insight (e.g., sales, inventory, customer behavior).
                insightDescription:
                  type: string
                  description: Description of the actionable insight.
                impactLevel:
                  type: string
                  description: Impact level of the insight (e.g., low, medium, high).
                recommendedActions:
                  type: array
                  items:
                    type: string
                  description: Recommended actions based on the insight.
                analysisDetails:
                  type: string
                  description: Detailed analysis of the insight data.
              required:
                - insightCategory
                - insightDescription
                - impactLevel
      responses:
        '201':
          description: Actionable retail insights data successfully submitted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  insightId:
                    type: string
                    description: Unique identifier of the submitted insight.
                  status:
                    type: string
                    description: Status of the insight (e.g., submitted, under review).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/analytics/actionable-insights/reports':
    get:
      summary: Retrieve actionable retail insights reports
      description: Fetch detailed reports on actionable retail insights.
      parameters:
        - name: timeframe
          in: query
          required: true
          schema:
            type: string
            enum: [monthly, quarterly, yearly]
          description: Timeframe for the actionable retail insights report.
      responses:
        '200':
          description: Successful retrieval of actionable retail insights reports.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reportId:
                      type: string
                      description: Unique identifier of the actionable retail insights report.
                    timeframe:
                      type: string
                      description: Timeframe covered by the report.
                    generatedInsights:
                      type: array
                      items:
                        type: object
                        properties:
                          insightCategory:
                            type: string
                            description: Category of the insight.
                          insightDescription:
                            type: string
                            description: Description of the actionable insight.
                          impactLevel:
                            type: string
                            description: Impact level of the insight.
                          recommendedActions:
                            type: array
                            items:
                              type: string
                            description: Recommended actions based on the insight.
                    overallInsightImpact:
                      type: string
                      description: Overall assessment of the impact of insights during the timeframe.
        '400':
          description: Missing or invalid timeframe parameter.
        '500':
          description: Internal server error.