openapi: 3.0.0
info:
  title: Chatbots For Shareholder Engagement
  version: 1.0.0
  description: >
    API to manage and optimize the use of chatbots for shareholder engagement in retail,
    ensuring efficient communication, improved shareholder satisfaction, and enhanced investor relations.

paths:
  '/shareholder/engagement/chatbots':
    get:
      summary: Analyze chatbot efficiency for shareholder engagement
      description: Retrieve analysis and recommendations for improving chatbot performance in shareholder engagement.
      responses:
        '200':
          description: Successful retrieval of chatbot performance data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalQueriesHandled:
                    type: integer
                    description: Total number of shareholder queries handled by chatbots.
                  queriesResolvedSuccessfully:
                    type: integer
                    description: Number of shareholder queries resolved successfully by chatbots.
                  optimizationSuggestions:
                    type: array
                    items:
                      type: object
                      properties:
                        queryType:
                          type: string
                          description: Type of shareholder query (e.g., financial performance, governance, dividends).
                        suggestion:
                          type: string
                          description: Optimization recommendation for the query type.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/shareholder/engagement/chatbots/simulation':
    post:
      summary: Simulate chatbot scenarios for shareholder engagement
      description: Create and simulate scenarios for optimizing chatbot performance in shareholder engagement.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                storeId:
                  type: string
                  description: Unique identifier of the retail store.
                queryCategories:
                  type: array
                  items:
                    type: string
                  description: Categories of shareholder queries (e.g., financial performance, governance, dividends).
                chatbotStrategies:
                  type: array
                  items:
                    type: string
                  description: Strategies for chatbot optimization (e.g., natural language processing, sentiment analysis, machine learning).
              required:
                - storeId
                - queryCategories
                - chatbotStrategies
      responses:
        '201':
          description: Chatbot simulation for shareholder engagement successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulationId:
                    type: string
                    description: Unique identifier of the chatbot simulation.
                  status:
                    type: string
                    description: Current status of the simulation (e.g., in-progress, completed).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/optimization/shareholder/engagement/chatbots':
    get:
      summary: Retrieve chatbot optimization suggestions for shareholder engagement
      description: Get chatbot optimization recommendations for shareholder engagement based on analysis.
      parameters:
        - name: storeId
          in: query
          required: true
          schema:
            type: string
          description: Unique identifier of the retail store.
      responses:
        '200':
          description: Successful retrieval of chatbot optimization suggestions.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    queryType:
                      type: string
                      description: Type of shareholder query (e.g., financial performance, governance, dividends).
                    recommendation:
                      type: string
                      description: Suggested improvement for chatbot performance.
                    expectedImpact:
                      type: string
                      description: Anticipated outcome of the recommendation (e.g., improved shareholder satisfaction, enhanced investor relations).
        '400':
          description: Missing or invalid storeId parameter.
        '500':
          description: Internal server error.