openapi: 3.0.0
info:
  title: Continuous Optimization Of Retail Processes
  version: 1.0.0
  description: >
    API to manage the continuous optimization of retail processes, enabling businesses
    to improve efficiency, reduce costs, and enhance customer satisfaction through
    ongoing process improvements.

paths:
  '/process-optimization/retail':
    get:
      summary: Retrieve process optimization data
      description: Fetch details of continuous optimization efforts for retail processes.
      responses:
        '200':
          description: Successful retrieval of process optimization data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  optimizationId:
                    type: string
                    description: Unique identifier of the optimization effort.
                  processName:
                    type: string
                    description: Name of the retail process being optimized.
                  optimizationMetrics:
                    type: object
                    properties:
                      efficiencyImprovement:
                        type: number
                        description: Percentage improvement in process efficiency.
                      costReduction:
                        type: number
                        description: Percentage reduction in process costs.
                      customerSatisfactionScore:
                        type: number
                        description: Improvement in customer satisfaction score (0-100).
                  optimizationActions:
                    type: array
                    items:
                      type: string
                    description: Actions taken to optimize the process.
                  lastUpdated:
                    type: string
                    format: date-time
                    description: Timestamp of the last update to the optimization effort.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/process-optimization/retail/submit':
    post:
      summary: Submit data for process optimization
      description: Submit data for continuous optimization of retail processes.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                processName:
                  type: string
                  description: Name of the retail process being optimized.
                optimizationMetrics:
                  type: object
                  properties:
                    efficiencyImprovement:
                      type: number
                      description: Percentage improvement in process efficiency.
                    costReduction:
                      type: number
                      description: Percentage reduction in process costs.
                    customerSatisfactionScore:
                      type: number
                      description: Improvement in customer satisfaction score (0-100).
                  required:
                    - efficiencyImprovement
                    - costReduction
                    - customerSatisfactionScore
                optimizationActions:
                  type: array
                  items:
                    type: string
                  description: Actions taken to optimize the process.
                analysisDetails:
                  type: string
                  description: Detailed analysis of the optimization data.
              required:
                - processName
                - optimizationMetrics
                - optimizationActions
      responses:
        '201':
          description: Process optimization data successfully submitted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  optimizationId:
                    type: string
                    description: Unique identifier of the submitted optimization effort.
                  status:
                    type: string
                    description: Status of the optimization (e.g., submitted, under review).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/process-optimization/retail/reports':
    get:
      summary: Retrieve process optimization reports
      description: Fetch detailed reports on continuous optimization of retail processes.
      parameters:
        - name: timeframe
          in: query
          required: true
          schema:
            type: string
            enum: [monthly, quarterly, yearly]
          description: Timeframe for the process optimization report.
      responses:
        '200':
          description: Successful retrieval of process optimization reports.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reportId:
                      type: string
                      description: Unique identifier of the process optimization report.
                    timeframe:
                      type: string
                      description: Timeframe covered by the report.
                    optimizedProcesses:
                      type: array
                      items:
                        type: object
                        properties:
                          processName:
                            type: string
                            description: Name of the retail process.
                          optimizationMetrics:
                            type: object
                            properties:
                              efficiencyImprovement:
                                type: number
                                description: Percentage improvement in process efficiency.
                              costReduction:
                                type: number
                                description: Percentage reduction in process costs.
                              customerSatisfactionScore:
                                type: number
                                description: Improvement in customer satisfaction score.
                          optimizationActions:
                            type: array
                            items:
                              type: string
                            description: Actions taken to optimize the process.
                    overallOptimizationImpact:
                      type: string
                      description: Overall assessment of optimization impact during the timeframe.
        '400':
          description: Missing or invalid timeframe parameter.
        '500':
          description: Internal server error.