openapi: 3.0.0
info:
  title: 'Dynamic Distribution Planning in Retail'
  description: 'API for dynamic distribution planning in retail, focusing on automation and search functionalities to optimize distribution processes.'
  version: 1.0.0
paths:
  '/distribution/planning/dynamic/manage':
    post:
      summary: 'Manage dynamic distribution planning'
      description: 'Optimizes distribution planning dynamically to ensure efficient and timely delivery of products in retail.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                process_id:
                  type: integer
                retail_domain_category:
                  type: string
                process_group:
                  type: string
                distribution_data:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: string
                      distribution_center_id:
                        type: string
                      delivery_schedule:
                        type: string
                      optimization_recommendations:
                        type: array
                        items:
                          type: string
      responses:
        '200':
          description: 'Dynamic distribution planning managed successfully'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updated_distribution_data:
                    type: array
                    items:
                      type: object
                      properties:
                        product_id:
                          type: string
                        distribution_center_id:
                          type: string
                        delivery_schedule:
                          type: string
                        optimization_recommendations:
                          type: array
                          items:
                            type: string
  '/distribution/planning/dynamic/search':
    get:
      summary: 'Search dynamic distribution planning data'
      description: 'Search for dynamic distribution planning data based on product ID or distribution center ID.'
      parameters:
        - name: 'product_id'
          in: query
          schema:
            type: string
          required: false
          description: 'ID of the product to search for'
        - name: 'distribution_center_id'
          in: query
          schema:
            type: string
          required: false
          description: 'ID of the distribution center to search for'
      responses:
        '200':
          description: 'Dynamic distribution planning data found'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    product_id:
                      type: string
                    distribution_center_id:
                      type: string
                    delivery_schedule:
                      type: string
                    optimization_recommendations:
                      type: array
                      items:
                        type: string