openapi: 3.0.0
info:
  title: Enhanced Retail Workspace Optimization
  version: 1.0.0
  description: >
    API for optimizing retail workspace planning and acquisition, facilitating better 
    utilization of space, cost efficiency, and operational effectiveness.

paths:
  '/workspace/planning':
    get:
      summary: Retrieve workspace planning data
      description: Fetch data and insights for planning optimized retail workspaces.
      responses:
        '200':
          description: Successful retrieval of workspace planning data.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    workspaceId:
                      type: string
                      description: Unique identifier for the workspace.
                    suggestedUsage:
                      type: string
                      description: Recommended usage for the workspace (e.g., storage, sales floor).
                    optimizationScore:
                      type: number
                      description: Score indicating the optimization level for the workspace.
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error

  '/workspace/acquisition':
    post:
      summary: Submit a workspace acquisition request
      description: Request the acquisition of new workspace areas for retail operations.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                workspaceType:
                  type: string
                  description: Type of workspace required (e.g., warehouse, retail space).
                area:
                  type: number
                  description: Area of the workspace in square meters.
                urgencyLevel:
                  type: string
                  description: Urgency of the acquisition (e.g., high, medium, low).
              required:
                - workspaceType
                - area
                - urgencyLevel
      responses:
        '201':
          description: Workspace acquisition request successfully submitted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    description: Unique identifier for the acquisition request.
                  status:
                    type: string
                    description: Current status of the request (e.g., pending, approved).
        '400':
          description: Invalid request body
        '500':
          description: Internal server error

  '/workspace/analysis':
    get:
      summary: Analyze workspace utilization
      description: Retrieve analysis of workspace utilization for ongoing optimization.
      responses:
        '200':
          description: Successful retrieval of workspace utilization analysis.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalWorkspace:
                    type: number
                    description: Total workspace area in use (in square meters).
                  utilizationRate:
                    type: number
                    description: Percentage of workspace utilized effectively.
                  underutilizedSpaces:
                    type: array
                    items:
                      type: object
                      properties:
                        workspaceId:
                          type: string
                          description: Unique identifier for the workspace.
                        area:
                          type: number
                          description: Area of the workspace in square meters.
                        suggestedOptimization:
                          type: string
                          description: Recommendations for better utilization of the workspace.
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error
