openapi: 3.0.0
info:
  title: 'Enhancing Service Management Insights'
  description: 'This API is designed to improve service management by providing insights into performance trends, customer feedback, and operational efficiency. It enables businesses to track, analyze, and optimize service delivery for better decision-making and customer satisfaction.'
  version: 1.0.0
paths:
  '/service-insights':
    get:
      summary: 'Retrieve a list of service management insights'
      description: 'Fetches a list of all service management insights being enhanced.'
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    insightId:
                      type: string
                      description: 'Unique identifier for the service management insight'
                    insightName:
                      type: string
                      description: 'Name of the insight (e.g., performance trends, customer feedback, operational efficiency)'
                    createdDate:
                      type: string
                      format: date
                      description: 'Date the insight was created'
                    lastUpdatedDate:
                      type: string
                      format: date
                      description: 'Date the insight was last updated'
                    status:
                      type: string
                      description: 'Status of the insight (e.g., active, archived, under review)'
                  required:
                    - insightId
                    - insightName
                    - createdDate
                    - status
    post:
      summary: 'Add a new service management insight'
      description: 'Adds a new service management insight to the system.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                insightName:
                  type: string
                  description: 'Name of the insight (e.g., performance trends, customer feedback, operational efficiency)'
                createdDate:
                  type: string
                  format: date
                  description: 'Date the insight was created'
                lastUpdatedDate:
                  type: string
                  format: date
                  description: 'Date the insight was last updated'
                status:
                  type: string
                  description: 'Status of the insight (e.g., active, archived, under review)'
              required:
                - insightName
                - createdDate
                - status
      responses:
        '201':
          description: 'Service management insight created successfully'
  '/service-insights/{insightId}':
    get:
      summary: 'Retrieve details of a specific service management insight'
      description: 'Fetches details of a specific service management insight by its ID.'
      parameters:
        - name: 'insightId'
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: object
                properties:
                  insightId:
                    type: string
                    description: 'Unique identifier for the service management insight'
                  insightName:
                    type: string
                    description: 'Name of the insight (e.g., performance trends, customer feedback, operational efficiency)'
                  createdDate:
                    type: string
                    format: date
                    description: 'Date the insight was created'
                  lastUpdatedDate:
                    type: string
                    format: date
                    description: 'Date the insight was last updated'
                  status:
                    type: string
                    description: 'Status of the insight (e.g., active, archived, under review)'
                required:
                  - insightId
                  - insightName
                  - createdDate
                  - status
    put:
      summary: 'Update an existing service management insight'
      description: 'Updates details of an existing service management insight by its ID.'
      parameters:
        - name: 'insightId'
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                insightName:
                  type: string
                  description: 'Name of the insight (e.g., performance trends, customer feedback, operational efficiency)'
                createdDate:
                  type: string
                  format: date
                  description: 'Date the insight was created'
                lastUpdatedDate:
                  type: string
                  format: date
                  description: 'Date the insight was last updated'
                status:
                  type: string
                  description: 'Status of the insight (e.g., active, archived, under review)'
              required:
                - insightName
                - createdDate
                - status
      responses:
        '200':
          description: 'Service management insight updated successfully'
    delete:
      summary: 'Delete a service management insight'
      description: 'Deletes a service management insight from the system by its ID.'
      parameters:
        - name: 'insightId'
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'Service management insight deleted successfully'