openapi: 3.0.0
info:
  title: Optimized Maintenance Scheduling In Retail Operations
  version: 1.0.0
  description: >
    API to manage and optimize maintenance scheduling in retail operations,
    ensuring efficient resource allocation, reduced downtime, and cost-effective maintenance strategies.

paths:
  '/maintenance/scheduling':
    get:
      summary: Analyze maintenance scheduling efficiency
      description: Retrieve analysis and recommendations for improving maintenance scheduling in retail operations.
      responses:
        '200':
          description: Successful retrieval of maintenance scheduling data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalScheduledTasks:
                    type: integer
                    description: Total number of maintenance tasks scheduled.
                  tasksCompletedOnTime:
                    type: integer
                    description: Number of tasks completed within the scheduled time.
                  optimizationSuggestions:
                    type: array
                    items:
                      type: object
                      properties:
                        taskType:
                          type: string
                          description: Type of maintenance task (e.g., electrical, plumbing, HVAC).
                        suggestion:
                          type: string
                          description: Optimization recommendation for the task type.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/maintenance/scheduling/simulation':
    post:
      summary: Simulate maintenance scheduling scenarios
      description: Create and simulate scenarios for optimizing maintenance scheduling in retail operations.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                storeId:
                  type: string
                  description: Unique identifier of the retail store.
                maintenanceCategories:
                  type: array
                  items:
                    type: string
                  description: Categories of maintenance tasks (e.g., electrical, plumbing, HVAC).
                schedulingStrategies:
                  type: array
                  items:
                    type: string
                  description: Strategies for maintenance scheduling (e.g., priority-based, time-based, resource-based).
              required:
                - storeId
                - maintenanceCategories
                - schedulingStrategies
      responses:
        '201':
          description: Maintenance scheduling simulation successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulationId:
                    type: string
                    description: Unique identifier of the maintenance scheduling simulation.
                  status:
                    type: string
                    description: Current status of the simulation (e.g., in-progress, completed).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/optimization/maintenance/scheduling':
    get:
      summary: Retrieve maintenance scheduling optimization suggestions
      description: Get maintenance scheduling optimization recommendations based on analysis.
      parameters:
        - name: storeId
          in: query
          required: true
          schema:
            type: string
          description: Unique identifier of the retail store.
      responses:
        '200':
          description: Successful retrieval of maintenance scheduling optimization suggestions.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    taskType:
                      type: string
                      description: Type of maintenance task (e.g., electrical, plumbing, HVAC).
                    recommendation:
                      type: string
                      description: Suggested improvement for maintenance scheduling.
                    expectedImpact:
                      type: string
                      description: Anticipated outcome of the recommendation (e.g., reduced downtime, cost savings).
        '400':
          description: Missing or invalid storeId parameter.
        '500':
          description: Internal server error.