openapi: 3.0.0
info:
  title: Performance Strategy Management In Retail
  version: 1.0.0
  description: >
    API to manage performance strategy in retail, enabling businesses to define,
    monitor, and optimize strategies to achieve operational and financial goals.

paths:
  '/performance-strategy/management':
    get:
      summary: Retrieve performance strategy data
      description: Fetch details of performance strategies and their current status.
      responses:
        '200':
          description: Successful retrieval of performance strategy data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  strategyId:
                    type: string
                    description: Unique identifier of the performance strategy.
                  strategyName:
                    type: string
                    description: Name of the performance strategy.
                  objectives:
                    type: array
                    items:
                      type: string
                    description: Objectives of the performance strategy.
                  keyMetrics:
                    type: object
                    properties:
                      salesGrowth:
                        type: number
                        description: Target sales growth percentage.
                      customerSatisfaction:
                        type: number
                        description: Target customer satisfaction score.
                      operationalEfficiency:
                        type: number
                        description: Target operational efficiency score.
                  status:
                    type: string
                    description: Status of the strategy (e.g., active, completed, on-hold).
                  lastUpdated:
                    type: string
                    format: date-time
                    description: Timestamp of the last update to the strategy.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/performance-strategy/management/submit':
    post:
      summary: Submit a new performance strategy
      description: Submit a new performance strategy for retail operations.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                strategyName:
                  type: string
                  description: Name of the performance strategy.
                objectives:
                  type: array
                  items:
                    type: string
                  description: Objectives of the performance strategy.
                keyMetrics:
                  type: object
                  properties:
                    salesGrowth:
                      type: number
                      description: Target sales growth percentage.
                    customerSatisfaction:
                      type: number
                      description: Target customer satisfaction score.
                    operationalEfficiency:
                      type: number
                      description: Target operational efficiency score.
                  required:
                    - salesGrowth
                    - customerSatisfaction
                    - operationalEfficiency
                analysisDetails:
                  type: string
                  description: Detailed analysis of the performance strategy.
              required:
                - strategyName
                - objectives
                - keyMetrics
      responses:
        '201':
          description: Performance strategy successfully submitted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  strategyId:
                    type: string
                    description: Unique identifier of the submitted strategy.
                  status:
                    type: string
                    description: Status of the strategy (e.g., submitted, under review).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/performance-strategy/management/reports':
    get:
      summary: Retrieve performance strategy reports
      description: Fetch detailed reports on performance strategies and their outcomes.
      parameters:
        - name: timeframe
          in: query
          required: true
          schema:
            type: string
            enum: [monthly, quarterly, yearly]
          description: Timeframe for the performance strategy report.
      responses:
        '200':
          description: Successful retrieval of performance strategy reports.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reportId:
                      type: string
                      description: Unique identifier of the performance strategy report.
                    timeframe:
                      type: string
                      description: Timeframe covered by the report.
                    strategies:
                      type: array
                      items:
                        type: object
                        properties:
                          strategyName:
                            type: string
                            description: Name of the performance strategy.
                          objectives:
                            type: array
                            items:
                              type: string
                            description: Objectives of the performance strategy.
                          keyMetrics:
                            type: object
                            properties:
                              salesGrowth:
                                type: number
                                description: Achieved sales growth percentage.
                              customerSatisfaction:
                                type: number
                                description: Achieved customer satisfaction score.
                              operationalEfficiency:
                                type: number
                                description: Achieved operational efficiency score.
                          status:
                            type: string
                            description: Status of the strategy (e.g., active, completed).
                    overallPerformanceAssessment:
                      type: string
                      description: Overall assessment of performance strategies during the timeframe.
        '400':
          description: Missing or invalid timeframe parameter.
        '500':
          description: Internal server error.