openapi: 3.0.0
info:
  title: Performance Evaluation In Retail Operations
  version: 1.0.0
  description: >
    API to manage performance evaluation in retail operations, enabling businesses to
    measure, analyze, and improve operational efficiency and effectiveness.

paths:
  '/performance-evaluation/retail':
    get:
      summary: Retrieve performance evaluation data
      description: Fetch performance metrics and evaluation results for retail operations.
      responses:
        '200':
          description: Successful retrieval of performance evaluation data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  evaluationId:
                    type: string
                    description: Unique identifier of the performance evaluation.
                  operationName:
                    type: string
                    description: Name of the retail operation being evaluated.
                  performanceMetrics:
                    type: object
                    properties:
                      efficiencyScore:
                        type: number
                        description: Efficiency score of the operation (0-100).
                      throughputTime:
                        type: number
                        description: Average throughput time of the operation.
                      errorRate:
                        type: number
                        description: Error rate in the operation.
                      customerSatisfactionScore:
                        type: number
                        description: Customer satisfaction score (0-100).
                  evaluationResults:
                    type: array
                    items:
                      type: string
                    description: Key findings and evaluation results.
                  lastUpdated:
                    type: string
                    format: date-time
                    description: Timestamp of the last update to the evaluation.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/performance-evaluation/retail/submit':
    post:
      summary: Submit data for performance evaluation
      description: Submit operational data for performance evaluation in retail.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                operationName:
                  type: string
                  description: Name of the retail operation being evaluated.
                performanceMetrics:
                  type: object
                  properties:
                    efficiencyScore:
                      type: number
                      description: Efficiency score of the operation (0-100).
                    throughputTime:
                      type: number
                      description: Average throughput time of the operation.
                    errorRate:
                      type: number
                      description: Error rate in the operation.
                    customerSatisfactionScore:
                      type: number
                      description: Customer satisfaction score (0-100).
                  required:
                    - efficiencyScore
                    - throughputTime
                    - errorRate
                    - customerSatisfactionScore
                analysisDetails:
                  type: string
                  description: Detailed analysis of the operational data.
              required:
                - operationName
                - performanceMetrics
      responses:
        '201':
          description: Performance evaluation data successfully submitted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  evaluationId:
                    type: string
                    description: Unique identifier of the submitted evaluation.
                  status:
                    type: string
                    description: Status of the evaluation (e.g., submitted, under review).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/performance-evaluation/retail/reports':
    get:
      summary: Retrieve performance evaluation reports
      description: Fetch detailed reports on performance evaluation in retail operations.
      parameters:
        - name: timeframe
          in: query
          required: true
          schema:
            type: string
            enum: [monthly, quarterly, yearly]
          description: Timeframe for the performance evaluation report.
      responses:
        '200':
          description: Successful retrieval of performance evaluation reports.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reportId:
                      type: string
                      description: Unique identifier of the performance evaluation report.
                    timeframe:
                      type: string
                      description: Timeframe covered by the report.
                    evaluatedOperations:
                      type: array
                      items:
                        type: object
                        properties:
                          operationName:
                            type: string
                            description: Name of the retail operation.
                          performanceMetrics:
                            type: object
                            properties:
                              efficiencyScore:
                                type: number
                                description: Efficiency score of the operation.
                              throughputTime:
                                type: number
                                description: Average throughput time of the operation.
                              errorRate:
                                type: number
                                description: Error rate in the operation.
                              customerSatisfactionScore:
                                type: number
                                description: Customer satisfaction score.
                          evaluationResults:
                            type: array
                            items:
                              type: string
                            description: Key findings and evaluation results.
                    overallOperationalPerformance:
                      type: string
                      description: Overall assessment of operational performance during the timeframe.
        '400':
          description: Missing or invalid timeframe parameter.
        '500':
          description: Internal server error.