openapi: 3.0.0
info:
  title: Predictive Analytics In Project Management
  version: 1.0.0
  description: >
    API to manage predictive analytics in project management, enabling businesses to
    forecast project outcomes, identify risks, and optimize resource allocation.

paths:
  '/predictive-analytics/project-management':
    get:
      summary: Retrieve predictive analytics data
      description: Fetch predictive analytics insights for project management.
      responses:
        '200':
          description: Successful retrieval of predictive analytics data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  analyticsId:
                    type: string
                    description: Unique identifier of the predictive analytics report.
                  projectId:
                    type: string
                    description: Unique identifier of the project.
                  predictedOutcome:
                    type: string
                    description: Predicted outcome of the project (e.g., on-time, delayed, over-budget).
                  riskAssessment:
                    type: array
                    items:
                      type: object
                      properties:
                        riskType:
                          type: string
                          description: Type of risk (e.g., resource, timeline, budget).
                        likelihood:
                          type: string
                          description: Likelihood of the risk occurring (e.g., low, medium, high).
                        impact:
                          type: string
                          description: Potential impact of the risk (e.g., minor, major, critical).
                  optimizationSuggestions:
                    type: array
                    items:
                      type: string
                    description: Suggestions for optimizing project performance.
                  lastUpdated:
                    type: string
                    format: date-time
                    description: Timestamp of the last update to the analytics.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/predictive-analytics/project-management/submit':
    post:
      summary: Submit data for predictive analytics
      description: Submit project data for predictive analytics and risk assessment.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: string
                  description: Unique identifier of the project.
                projectData:
                  type: object
                  properties:
                    timeline:
                      type: string
                      format: date
                      description: Project timeline.
                    budget:
                      type: number
                      description: Project budget.
                    resourceAllocation:
                      type: array
                      items:
                        type: object
                        properties:
                          resourceType:
                            type: string
                            description: Type of resource (e.g., personnel, equipment).
                          quantity:
                            type: integer
                            description: Quantity of the resource.
                  required:
                    - timeline
                    - budget
                    - resourceAllocation
                analysisDetails:
                  type: string
                  description: Detailed analysis of the project data.
              required:
                - projectId
                - projectData
      responses:
        '201':
          description: Predictive analytics data successfully submitted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  analyticsId:
                    type: string
                    description: Unique identifier of the submitted analytics.
                  status:
                    type: string
                    description: Status of the analytics (e.g., submitted, under review).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/predictive-analytics/project-management/reports':
    get:
      summary: Retrieve predictive analytics reports
      description: Fetch detailed reports on predictive analytics for project management.
      parameters:
        - name: timeframe
          in: query
          required: true
          schema:
            type: string
            enum: [monthly, quarterly, yearly]
          description: Timeframe for the predictive analytics report.
      responses:
        '200':
          description: Successful retrieval of predictive analytics reports.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reportId:
                      type: string
                      description: Unique identifier of the predictive analytics report.
                    timeframe:
                      type: string
                      description: Timeframe covered by the report.
                    analyzedProjects:
                      type: array
                      items:
                        type: object
                        properties:
                          projectId:
                            type: string
                            description: Unique identifier of the project.
                          predictedOutcome:
                            type: string
                            description: Predicted outcome of the project.
                          riskAssessment:
                            type: array
                            items:
                              type: object
                              properties:
                                riskType:
                                  type: string
                                  description: Type of risk.
                                likelihood:
                                  type: string
                                  description: Likelihood of the risk occurring.
                                impact:
                                  type: string
                                  description: Potential impact of the risk.
                          optimizationSuggestions:
                            type: array
                            items:
                              type: string
                            description: Suggestions for optimizing project performance.
                    overallProjectPerformance:
                      type: string
                      description: Overall assessment of project performance during the timeframe.
        '400':
          description: Missing or invalid timeframe parameter.
        '500':
          description: Internal server error.