openapi: 3.0.0
info:
  title: 'Predictive IT Disruption Management in Retail'
  description: 'This API is designed to enable predictive IT disruption management in retail, leveraging AI and machine learning to predict and manage IT disruptions based on system logs and historical incidents. It supports the creation, retrieval, updating, and deletion of disruption management records to enhance efficiency and system reliability.'
  version: 1.0.0
paths:
  '/disruption-records':
    get:
      summary: 'Retrieve a list of disruption records'
      description: 'Fetches a list of all predictive IT disruption management records in retail.'
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    recordId:
                      type: string
                      description: 'Unique identifier for the disruption record'
                    processName:
                      type: string
                      description: 'Name of the disruption management process (e.g., IT disruption management)'
                    disruptionDate:
                      type: string
                      format: date
                      description: 'Date the disruption was predicted'
                    status:
                      type: string
                      description: 'Status of the disruption management (e.g., active, inactive, under review)'
                  required:
                    - recordId
                    - processName
                    - disruptionDate
                    - status
    post:
      summary: 'Add a new disruption record'
      description: 'Adds a new predictive IT disruption management record to the retail system.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                processName:
                  type: string
                  description: 'Name of the disruption management process (e.g., IT disruption management)'
                disruptionDate:
                  type: string
                  format: date
                  description: 'Date the disruption was predicted'
                status:
                  type: string
                  description: 'Status of the disruption management (e.g., active, inactive, under review)'
              required:
                - processName
                - disruptionDate
                - status
      responses:
        '201':
          description: 'Disruption record created successfully'
  '/disruption-records/{recordId}':
    get:
      summary: 'Retrieve details of a specific disruption record'
      description: 'Fetches details of a specific predictive IT disruption management record by its ID.'
      parameters:
        - name: 'recordId'
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: object
                properties:
                  recordId:
                    type: string
                    description: 'Unique identifier for the disruption record'
                  processName:
                    type: string
                    description: 'Name of the disruption management process (e.g., IT disruption management)'
                  disruptionDate:
                    type: string
                    format: date
                    description: 'Date the disruption was predicted'
                  status:
                    type: string
                    description: 'Status of the disruption management (e.g., active, inactive, under review)'
                required:
                  - recordId
                  - processName
                  - disruptionDate
                  - status
    put:
      summary: 'Update an existing disruption record'
      description: 'Updates details of an existing predictive IT disruption management record by its ID.'
      parameters:
        - name: 'recordId'
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                processName:
                  type: string
                  description: 'Name of the disruption management process (e.g., IT disruption management)'
                disruptionDate:
                  type: string
                  format: date
                  description: 'Date the disruption was predicted'
                status:
                  type: string
                  description: 'Status of the disruption management (e.g., active, inactive, under review)'
              required:
                - processName
                - disruptionDate
                - status
      responses:
        '200':
          description: 'Disruption record updated successfully'
    delete:
      summary: 'Delete a disruption record'
      description: 'Deletes a predictive IT disruption management record from the retail system by its ID.'
      parameters:
        - name: 'recordId'
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'Disruption record deleted successfully'