openapi: 3.0.0
info:
  title: 'Proactive Infrastructure Planning in Retail'
  description: 'This API is designed to enable proactive infrastructure planning in the retail sector, leveraging predictive analytics to optimize the deployment and management of IT infrastructure. It supports the creation, retrieval, updating, and deletion of infrastructure plans to ensure scalability and reliability.'
  version: 1.0.0
paths:
  '/infrastructure-plans':
    get:
      summary: 'Retrieve a list of infrastructure plans'
      description: 'Fetches a list of all proactive infrastructure plans in the retail system.'
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    planId:
                      type: string
                      description: 'Unique identifier for the infrastructure plan'
                    planName:
                      type: string
                      description: 'Name of the infrastructure plan (e.g., cloud migration, network expansion)'
                    createdDate:
                      type: string
                      format: date
                      description: 'Date the plan was created'
                    status:
                      type: string
                      description: 'Status of the plan (e.g., active, inactive, under review)'
                  required:
                    - planId
                    - planName
                    - createdDate
                    - status
    post:
      summary: 'Add a new infrastructure plan'
      description: 'Adds a new proactive infrastructure plan to the retail system.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                planName:
                  type: string
                  description: 'Name of the infrastructure plan (e.g., cloud migration, network expansion)'
                createdDate:
                  type: string
                  format: date
                  description: 'Date the plan was created'
                status:
                  type: string
                  description: 'Status of the plan (e.g., active, inactive, under review)'
              required:
                - planName
                - createdDate
                - status
      responses:
        '201':
          description: 'Infrastructure plan created successfully'
  '/infrastructure-plans/{planId}':
    get:
      summary: 'Retrieve details of a specific infrastructure plan'
      description: 'Fetches details of a specific proactive infrastructure plan by its ID.'
      parameters:
        - name: 'planId'
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Successful response'
          content:
            application/json:
              schema:
                type: object
                properties:
                  planId:
                    type: string
                    description: 'Unique identifier for the infrastructure plan'
                  planName:
                    type: string
                    description: 'Name of the infrastructure plan (e.g., cloud migration, network expansion)'
                  createdDate:
                    type: string
                    format: date
                    description: 'Date the plan was created'
                  status:
                    type: string
                    description: 'Status of the plan (e.g., active, inactive, under review)'
                required:
                  - planId
                  - planName
                  - createdDate
                  - status
    put:
      summary: 'Update an existing infrastructure plan'
      description: 'Updates details of an existing proactive infrastructure plan by its ID.'
      parameters:
        - name: 'planId'
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                planName:
                  type: string
                  description: 'Name of the infrastructure plan (e.g., cloud migration, network expansion)'
                createdDate:
                  type: string
                  format: date
                  description: 'Date the plan was created'
                status:
                  type: string
                  description: 'Status of the plan (e.g., active, inactive, under review)'
              required:
                - planName
                - createdDate
                - status
      responses:
        '200':
          description: 'Infrastructure plan updated successfully'
    delete:
      summary: 'Delete an infrastructure plan'
      description: 'Deletes a proactive infrastructure plan from the retail system by its ID.'
      parameters:
        - name: 'planId'
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'Infrastructure plan deleted successfully'