openapi: 3.0.0
info:
  title: Real Time Technician Guidance In Retail Maintenance
  version: 1.0.0
  description: >
    API to manage and optimize real-time technician guidance in retail maintenance,
    ensuring efficient issue resolution, reduced downtime, and improved maintenance outcomes.

paths:
  '/maintenance/guidance':
    get:
      summary: Analyze real-time technician guidance efficiency
      description: Retrieve analysis and recommendations for improving real-time technician guidance in retail maintenance.
      responses:
        '200':
          description: Successful retrieval of technician guidance data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalIssuesReported:
                    type: integer
                    description: Total number of maintenance issues reported.
                  issuesResolved:
                    type: integer
                    description: Number of issues resolved with real-time guidance.
                  optimizationSuggestions:
                    type: array
                    items:
                      type: object
                      properties:
                        issueType:
                          type: string
                          description: Type of maintenance issue (e.g., electrical, mechanical, HVAC).
                        suggestion:
                          type: string
                          description: Optimization recommendation for the issue type.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/maintenance/guidance/simulation':
    post:
      summary: Simulate real-time technician guidance scenarios
      description: Create and simulate scenarios for optimizing real-time technician guidance in retail maintenance.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                storeId:
                  type: string
                  description: Unique identifier of the retail store.
                issueCategories:
                  type: array
                  items:
                    type: string
                  description: Categories of maintenance issues (e.g., electrical, mechanical, HVAC).
                guidanceStrategies:
                  type: array
                  items:
                    type: string
                  description: Strategies for real-time guidance (e.g., augmented reality, remote assistance, step-by-step instructions).
              required:
                - storeId
                - issueCategories
                - guidanceStrategies
      responses:
        '201':
          description: Real-time technician guidance simulation successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulationId:
                    type: string
                    description: Unique identifier of the technician guidance simulation.
                  status:
                    type: string
                    description: Current status of the simulation (e.g., in-progress, completed).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/optimization/maintenance/guidance':
    get:
      summary: Retrieve real-time technician guidance optimization suggestions
      description: Get real-time technician guidance optimization recommendations based on analysis.
      parameters:
        - name: storeId
          in: query
          required: true
          schema:
            type: string
          description: Unique identifier of the retail store.
      responses:
        '200':
          description: Successful retrieval of technician guidance optimization suggestions.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    issueType:
                      type: string
                      description: Type of maintenance issue (e.g., electrical, mechanical, HVAC).
                    recommendation:
                      type: string
                      description: Suggested improvement for real-time technician guidance.
                    expectedImpact:
                      type: string
                      description: Anticipated outcome of the recommendation (e.g., reduced downtime, improved issue resolution).
        '400':
          description: Missing or invalid storeId parameter.
        '500':
          description: Internal server error.