openapi: 3.0.0
info:
  title: Revolutionary Retail Procurement Optimization
  version: 1.0.0
  description: >
    API for optimizing procurement processes in retail, enabling enhanced vendor management, 
    cost analysis, and streamlined asset acquisition.

paths:
  '/procurement/vendors':
    get:
      summary: Retrieve vendor list
      description: Fetch a list of all approved vendors for retail procurement.
      responses:
        '200':
          description: Successful retrieval of vendor list.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    vendorId:
                      type: string
                      description: Unique identifier for the vendor.
                    name:
                      type: string
                      description: Name of the vendor.
                    rating:
                      type: number
                      description: Vendor rating based on performance.
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error

  '/procurement/assets':
    post:
      summary: Request asset acquisition
      description: Submit a request for acquiring new assets for retail operations.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assetName:
                  type: string
                  description: Name of the asset to be acquired.
                quantity:
                  type: integer
                  description: Quantity of the asset to be acquired.
                urgencyLevel:
                  type: string
                  description: Urgency of the acquisition (e.g., high, medium, low).
              required:
                - assetName
                - quantity
                - urgencyLevel
      responses:
        '201':
          description: Asset acquisition request successfully submitted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    description: Unique identifier for the acquisition request.
                  status:
                    type: string
                    description: Current status of the request (e.g., pending, approved).
        '400':
          description: Invalid request body
        '500':
          description: Internal server error

  '/procurement/cost-analysis':
    get:
      summary: Fetch procurement cost analysis
      description: Retrieve detailed cost analysis for recent procurement activities.
      responses:
        '200':
          description: Successful retrieval of cost analysis.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalSpend:
                    type: number
                    description: Total spend on procurement activities.
                  breakdown:
                    type: array
                    items:
                      type: object
                      properties:
                        category:
                          type: string
                          description: Category of spend (e.g., assets, vendors).
                        amount:
                          type: number
                          description: Amount spent in the category.
        '400':
          description: Invalid request parameters
        '500':
          description: Internal server error
