openapi: 3.0.0
info:
  title: Risk Management In Retail Construction Projects
  version: 1.0.0
  description: >
    API to manage and mitigate risks in retail construction projects,
    ensuring timely completion, cost control, and quality assurance.

paths:
  '/risk/construction':
    get:
      summary: Analyze construction project risks
      description: Retrieve analysis and recommendations for managing risks in retail construction projects.
      responses:
        '200':
          description: Successful retrieval of construction risk data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalRisksIdentified:
                    type: integer
                    description: Total number of risks identified.
                  highPriorityRisks:
                    type: integer
                    description: Number of high-priority risks.
                  optimizationSuggestions:
                    type: array
                    items:
                      type: object
                      properties:
                        riskType:
                          type: string
                          description: Type of risk (e.g., financial, operational, safety).
                        suggestion:
                          type: string
                          description: Risk mitigation recommendation for the risk type.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/risk/simulation':
    post:
      summary: Simulate risk management scenarios
      description: Create and simulate scenarios for managing risks in retail construction projects.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: string
                  description: Unique identifier of the construction project.
                riskCategories:
                  type: array
                  items:
                    type: string
                  description: Categories of risks (e.g., financial, operational, safety).
                mitigationStrategies:
                  type: array
                  items:
                    type: string
                  description: Strategies for risk mitigation (e.g., contingency planning, insurance, safety protocols).
              required:
                - projectId
                - riskCategories
                - mitigationStrategies
      responses:
        '201':
          description: Risk management simulation successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulationId:
                    type: string
                    description: Unique identifier of the risk management simulation.
                  status:
                    type: string
                    description: Current status of the simulation (e.g., in-progress, completed).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/optimization/risk':
    get:
      summary: Retrieve risk management optimization suggestions
      description: Get risk management optimization recommendations based on analysis.
      parameters:
        - name: projectId
          in: query
          required: true
          schema:
            type: string
          description: Unique identifier of the construction project.
      responses:
        '200':
          description: Successful retrieval of risk management optimization suggestions.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    riskType:
                      type: string
                      description: Type of risk (e.g., financial, operational, safety).
                    recommendation:
                      type: string
                      description: Suggested improvement for risk management.
                    expectedImpact:
                      type: string
                      description: Anticipated outcome of the recommendation (e.g., reduced delays, cost savings).
        '400':
          description: Missing or invalid projectId parameter.
        '500':
          description: Internal server error.