openapi: 3.0.0
info:
  title: Strategic Market Exits In Retail
  version: 1.0.0
  description: >
    API to manage and optimize strategic market exits in retail environments,
    ensuring efficient withdrawal from markets, cost reduction, and alignment with business objectives.

paths:
  '/market/exit':
    get:
      summary: Analyze strategic market exits
      description: Retrieve analysis and recommendations for improving strategic market exits in retail.
      responses:
        '200':
          description: Successful retrieval of strategic market exit data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalMarketsConsidered:
                    type: integer
                    description: Total number of markets considered for exit.
                  marketsExited:
                    type: integer
                    description: Number of markets successfully exited.
                  optimizationSuggestions:
                    type: array
                    items:
                      type: object
                      properties:
                        marketType:
                          type: string
                          description: Type of market (e.g., regional, demographic, product category).
                        suggestion:
                          type: string
                          description: Optimization recommendation for the market type.
        '400':
          description: Invalid request parameters.
        '500':
          description: Internal server error.

  '/market/exit/simulation':
    post:
      summary: Simulate strategic market exit scenarios
      description: Create and simulate scenarios for optimizing strategic market exits in retail.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                storeId:
                  type: string
                  description: Unique identifier of the retail store.
                marketCategories:
                  type: array
                  items:
                    type: string
                  description: Categories of markets (e.g., regional, demographic, product category).
                exitStrategies:
                  type: array
                  items:
                    type: string
                  description: Strategies for market exit (e.g., liquidation, divestiture, partnership dissolution).
              required:
                - storeId
                - marketCategories
                - exitStrategies
      responses:
        '201':
          description: Strategic market exit simulation successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulationId:
                    type: string
                    description: Unique identifier of the strategic market exit simulation.
                  status:
                    type: string
                    description: Current status of the simulation (e.g., in-progress, completed).
        '400':
          description: Invalid request body.
        '500':
          description: Internal server error.

  '/optimization/market/exit':
    get:
      summary: Retrieve strategic market exit optimization suggestions
      description: Get strategic market exit optimization recommendations based on analysis.
      parameters:
        - name: storeId
          in: query
          required: true
          schema:
            type: string
          description: Unique identifier of the retail store.
      responses:
        '200':
          description: Successful retrieval of strategic market exit optimization suggestions.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    marketType:
                      type: string
                      description: Type of market (e.g., regional, demographic, product category).
                    recommendation:
                      type: string
                      description: Suggested improvement for strategic market exit decisions.
                    expectedImpact:
                      type: string
                      description: Anticipated outcome of the recommendation (e.g., cost savings, improved focus).
        '400':
          description: Missing or invalid storeId parameter.
        '500':
          description: Internal server error.