openapi: 3.0.0
info:
  title: 'Streamlined Order Fulfillment in Retail'
  description: 'API for streamlined order fulfillment in retail, focusing on automation and search functionalities.'
  version: 1.0.0
paths:
  '/order-fulfillment/streamlined/manage':
    post:
      summary: 'Manage streamlined order fulfillment'
      description: 'Optimizes the order fulfillment process in retail to ensure efficiency and accuracy.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                process_id:
                  type: integer
                retail_domain_category:
                  type: string
                process_group:
                  type: string
                fulfillment_data:
                  type: array
                  items:
                    type: object
                    properties:
                      order_id:
                        type: string
                      fulfillment_status:
                        type: string
                        enum: ['Pending', 'Processing', 'Shipped', 'Delivered']
                      optimization_recommendations:
                        type: array
                        items:
                          type: string
      responses:
        '200':
          description: 'Order fulfillment streamlined successfully'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updated_fulfillment_data:
                    type: array
                    items:
                      type: object
                      properties:
                        order_id:
                          type: string
                        fulfillment_status:
                          type: string
                          enum: ['Pending', 'Processing', 'Shipped', 'Delivered']
                        optimization_recommendations:
                          type: array
                          items:
                            type: string
  '/order-fulfillment/streamlined/search':
    get:
      summary: 'Search streamlined order fulfillment data'
      description: 'Search for streamlined order fulfillment data based on order ID or fulfillment status.'
      parameters:
        - name: 'order_id'
          in: query
          schema:
            type: string
          required: false
          description: 'ID of the order to search for'
        - name: 'fulfillment_status'
          in: query
          schema:
            type: string
            enum: ['Pending', 'Processing', 'Shipped', 'Delivered']
          required: false
          description: 'Status of the fulfillment to search for'
      responses:
        '200':
          description: 'Streamlined order fulfillment data found'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    order_id:
                      type: string
                    fulfillment_status:
                      type: string
                      enum: ['Pending', 'Processing', 'Shipped', 'Delivered']
                    optimization_recommendations:
                      type: array
                      items:
                        type: string