openapi: 3.0.0
info:
  title: 'Workforce Optimization in Warehouse Operations'
  description: 'API for workforce optimization in warehouse operations, focusing on automation and search functionalities to improve efficiency and productivity.'
  version: 1.0.0
paths:
  '/warehouse/workforce/optimize':
    post:
      summary: 'Optimize workforce in warehouse operations'
      description: 'Optimizes workforce allocation and scheduling in warehouse operations to enhance productivity and reduce costs.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                process_id:
                  type: integer
                retail_domain_category:
                  type: string
                process_group:
                  type: string
                workforce_data:
                  type: array
                  items:
                    type: object
                    properties:
                      employee_id:
                        type: string
                      role:
                        type: string
                      shift_schedule:
                        type: string
                      optimization_recommendations:
                        type: array
                        items:
                          type: string
      responses:
        '200':
          description: 'Workforce optimization executed successfully'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  updated_workforce_data:
                    type: array
                    items:
                      type: object
                      properties:
                        employee_id:
                          type: string
                        role:
                          type: string
                        shift_schedule:
                          type: string
                        optimization_recommendations:
                          type: array
                          items:
                            type: string
  '/warehouse/workforce/search':
    get:
      summary: 'Search workforce optimization data'
      description: 'Search for workforce optimization data based on employee ID or role.'
      parameters:
        - name: 'employee_id'
          in: query
          schema:
            type: string
          required: false
          description: 'ID of the employee to search for'
        - name: 'role'
          in: query
          schema:
            type: string
          required: false
          description: 'Role of the employee to search for'
      responses:
        '200':
          description: 'Workforce optimization data found'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    employee_id:
                      type: string
                    role:
                      type: string
                    shift_schedule:
                      type: string
                    optimization_recommendations:
                      type: array
                      items:
                        type: string
                        